module AuthAssistant
  module Generators
    class ClearGenerator < Rails::Generators::NamedBase
      desc "Clears the rails project from any artifacts generated by auth_assist" 

      def self.source_root
        @_devise_source_root ||= File.expand_path("../templates", __FILE__)
      end

      def get_strategy
        @strategy = AuthAssistant::Model.role_strategy
      end

      def generate_clear_migration
        case @strategy
        when :admin_field
          clear_migration_admin_field          
        when :role_field
          clear_migration_role_field        
        end
      end      
      
      protected
        def clear_migration_admin_field                
          say 'Generating clear migration for AdminField'
        end

        def clear_migration_role_field                
          say 'Generating clear migration for RoleField'
        end      
    end
  end
end