require 'generators/migration_helper'
require 'generators/reverse_migrations'
require 'generators/role_migrations'
require 'rake'

module AuthAssist
  module Generators
    class ClearGenerator < Rails::Generators::NamedBase       

      desc "Clears the rails project from any artifacts generated by auth_assist" 

      class_option :migration, :type => :boolean, :aliases => "-m", :default => true,
                                     :desc => "To generate a migration to clear the user role."
            
      def generate_clear_migration 
        return nil if !options[:migration]        
        clazz = AuthAssistance::RoleMigrations.clazz(name)
        clazz.new.generate_reverse_migration(name)
      end
    end
  end
end