require 'generators/migration_helper'
require 'rake'

module AuthAssist
  module Generators
    class ClearGenerator < Rails::Generators::NamedBase       

      desc "Clears the rails project from any artifacts generated by auth_assist" 

      class_option :migration, :type => :boolean, :aliases => "-m", :default => false,
                                     :desc => "To generate a migration to clear the user role."
            
      def get_strategy
        @strategy = AuthAssistant::Model.role_strategy
      end
      
      def generate_clear_migration
        case @strategy
        when :admin_field
          clear_migration_admin_field          
        when :role_field
          clear_migration_role_field        
        end
      end      
      
      protected
        def clear_migration_admin_field 
          return nil if !options[:migration]
          say 'Generating clear migration for AdminField'
          admin_field_migration             
          reverse_migration 'add_admin_field_to_user'
          run 'rake db:migrate'
        end
      
        def migration_dir
          File.join(Rails.root, 'db/migrate')          
        end
              
        def reverse_migration(name)
          # go into migrations dir
          FileUtils.cd migration_dir do
            mig_files = find_matching_files(name)
            reverse_migration_methods(mig_files.first) if !mig_files.empty?
          end          
        end
        
        def find_matching_files(name)
          FileList['*.rb'].reject{|f| (f =~ /#{Regexp.escape(name)}/) == nil }
        end
        
        def reverse_migration_methods(file) 
          new_name ="remove_#{strategy}"
          migration new_name
          FileUtil.cp file, find_matching_files(new_name).first 
          file_swap_content(File.new(new_name), 'self.up', 'self.down')
        end
        
        def file_reverse(file, str1, str2) 
          # use thor action          
          file.replace str1, str2
          file.replace str2, str1
        end  
      
        include ::AuthAssist::MigrationHelper  
    end
  end
end