require 'auth_assistant/role_strategies/shared'
require 'auth_assistant/role_strategies/admin_field'
require 'auth_assistant/role_strategies/role_field'
require 'auth_assistant/role_strategies/roles_field'
require 'auth_assistant/role_strategies/roles_mask'
require 'auth_assistant/role_strategies/role_assignment'
require 'auth_assistant/role_strategies/multi_role_assignment'