require 'auth_assistant/role_strategies/strategy_helper'
require 'auth_assistant/role_strategies/admin_field'
require 'auth_assistant/role_strategies/role_field'
require 'auth_assistant/role_strategies/roles_field'
require 'auth_assistant/role_strategies/roles_mask'
require 'auth_assistant/role_strategies/role_assignment'
